{
 "title": "Local",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Parachain Blocktime",
   "type": "stat",
   "description": "Average blocktime over a 10min window",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(1/rate(substrate_block_height{status=\"finalized\"}[10m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Blockchain metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Proposer Block Construction Time",
   "type": "timeseries",
   "description": "histogram 90th quantiles for time to construct a block (seconds) More info: https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(substrate_proposer_block_constructed_bucket[5m])) by (le))",
     "legendFormat": "Histogram"
    }
   ]
  },
  {
   "title": "Finalized Block Height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(substrate_block_height{status=\"finalized\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Finilized Blocks per Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(substrate_block_height{status=\"finalized\"}[1m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Storage Subscriber",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_storage_notification_subscribers{action=\"added\"} - ignoring(action) substrate_storage_notification_subscribers{action=\"removed\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Transactions (Ready)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_ready_transactions_number",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count"
    }
   ]
  }
 ]
}